services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Esa@Sql#2026!
      MSSQL_MEMORY_LIMIT_MB: "1600"
    ports:
      - "1433:1433"
